### ISSUE TITLE
Slides available

### ISSUE THREAD

**Issue by lgatto** [lgatto/2020_07_15_ISMB#1]
@sgibb @jorainer - the slides for the ISMB talk are online at https://lgatto.github.io/2020_07_15_ISMB_online/

Recording will follow, but in the meantime, feel free to comment/amend as you see fit.

**Comment by jorainer** [comment]
All fine from my side!

**Comment by jorainer** [comment]
Maybe one minor thing - would be nice if you could add our affiliations to the title page?

**Comment by sgibb** [comment]
Everything fine.

**Comment by lgatto** [comment]
@jorainer - I can do this and will **try** to get a new recording with the new slides.

**Comment by jorainer** [comment]
No worries, if it's that much of additional work you can also just leave it as it is.
